# Generated by Django 4.2.25 on 2025-10-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'bed',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dob', models.DateField(blank=True, help_text='Date of birth', null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admitted_timestamp', models.DateTimeField(auto_now_add=True)),
                ('discharge_timestamp', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admissions', to='src.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admissions', to='src.patient')),
            ],
            options={
                'db_table': 'admission',
            },
        ),
    ]
